import dotenv from "dotenv";
import mongoose from "mongoose";
import connectDB from "../config/db.js";
import Food from "../models/food.model.js";

dotenv.config();

const foods = [
  // Grains & Cereals
  {
    name: "Oats",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0.9,
    sodium: 2,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast"]
  },
  {
    name: "Brown Rice",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "White Rice",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Quinoa",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Whole Wheat Bread",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 13,
    carbs: 43,
    fat: 3.2,
    fiber: 6.5,
    sugar: 5,
    sodium: 480,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Lunch"]
  },
  {
    name: "White Bread",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.5,
    sugar: 5,
    sodium: 490,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Lunch"]
  },
  {
    name: "Pasta",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 0.5,
    fiber: 1.2,
    sugar: 0.7,
    sodium: 1,
    foodPreference: "Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Barley",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 123,
    protein: 2.3,
    carbs: 28.2,
    fat: 0.4,
    fiber: 3.8,
    sugar: 0.4,
    sodium: 4,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Millet",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 378,
    protein: 11,
    carbs: 72.8,
    fat: 4.2,
    fiber: 8.5,
    sugar: 0,
    sodium: 5,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Corn",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 3.2,
    carbs: 19,
    fat: 1.2,
    fiber: 2.7,
    sugar: 3.2,
    sodium: 15,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner", "Snacks"]
  },

  // Fruits
  {
    name: "Banana",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Apple",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Orange",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9.4,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Grapes",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    sugar: 15.5,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Strawberries",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Blueberries",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Mango",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    sugar: 13.7,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Pineapple",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    sugar: 9.9,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Watermelon",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    sugar: 6.2,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Kiwi",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3,
    sugar: 9,
    sodium: 3,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Avocado",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 7,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Lunch", "Snacks"]
  },
  {
    name: "Papaya",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 43,
    protein: 0.5,
    carbs: 10.8,
    fat: 0.3,
    fiber: 1.7,
    sugar: 7.8,
    sodium: 8,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Pomegranate",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 83,
    protein: 1.7,
    carbs: 18.7,
    fat: 1.2,
    fiber: 4,
    sugar: 13.7,
    sodium: 3,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Lemon",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 29,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.3,
    fiber: 2.8,
    sugar: 2.5,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Peach",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 39,
    protein: 0.9,
    carbs: 9.5,
    fat: 0.3,
    fiber: 1.5,
    sugar: 8.4,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Plum",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 46,
    protein: 0.7,
    carbs: 11.4,
    fat: 0.3,
    fiber: 1.4,
    sugar: 9.9,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Cherries",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 50,
    protein: 1.1,
    carbs: 12.2,
    fat: 0.3,
    fiber: 1.6,
    sugar: 8.5,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Raspberries",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 1.2,
    carbs: 11.9,
    fat: 0.7,
    fiber: 6.5,
    sugar: 4.4,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Blackberries",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 43,
    protein: 1.4,
    carbs: 9.6,
    fat: 0.5,
    fiber: 5.3,
    sugar: 4.9,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Cantaloupe",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 34,
    protein: 0.8,
    carbs: 8.2,
    fat: 0.2,
    fiber: 0.9,
    sugar: 7.9,
    sodium: 16,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },

  // Vegetables
  {
    name: "Broccoli",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 33,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Spinach",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Carrots",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner", "Snacks"]
  },
  {
    name: "Tomatoes",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner", "Snacks"]
  },
  {
    name: "Cucumber",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner", "Snacks"]
  },
  {
    name: "Bell Peppers",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 26,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 1.8,
    sugar: 4.2,
    sodium: 3,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Cauliflower",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.9,
    carbs: 4.9,
    fat: 0.3,
    fiber: 2,
    sugar: 1.9,
    sodium: 30,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Onions",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    sugar: 4.2,
    sodium: 4,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Garlic",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 149,
    protein: 6.4,
    carbs: 33.1,
    fat: 0.5,
    fiber: 2.1,
    sugar: 1,
    sodium: 17,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Ginger",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 80,
    protein: 1.8,
    carbs: 17.8,
    fat: 0.8,
    fiber: 2,
    sugar: 1.7,
    sodium: 13,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Sweet Potato",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 55,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Potato",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 2,
    carbs: 17.5,
    fat: 0.1,
    fiber: 2.2,
    sugar: 0.8,
    sodium: 6,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Mushrooms",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    sugar: 2,
    sodium: 5,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Zucchini",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    sugar: 2.5,
    sodium: 8,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Eggplant",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1,
    carbs: 5.9,
    fat: 0.2,
    fiber: 3,
    sugar: 3.5,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Asparagus",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    sugar: 1.9,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Green Beans",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
    fiber: 2.7,
    sugar: 3.3,
    sodium: 6,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Peas",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 81,
    protein: 5.4,
    carbs: 14.5,
    fat: 0.4,
    fiber: 5.1,
    sugar: 5.7,
    sodium: 5,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Corn",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 3.2,
    carbs: 19,
    fat: 1.2,
    fiber: 2.7,
    sugar: 3.2,
    sodium: 15,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner", "Snacks"]
  },
  {
    name: "Celery",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 0.7,
    carbs: 3.0,
    fat: 0.2,
    fiber: 1.6,
    sugar: 1.4,
    sodium: 80,
    foodPreference: "Vegan",
    mealType: ["Snacks", "Lunch"]
  },
  {
    name: "Radish",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
    fiber: 1.6,
    sugar: 1.9,
    sodium: 39,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Cabbage",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    fiber: 2.5,
    sugar: 3.2,
    sodium: 18,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },

  // Protein Foods
  {
    name: "Boiled Egg",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
    foodPreference: "Non-Vegetarian",
    mealType: ["Breakfast", "Lunch"]
  },
  {
    name: "Chicken Breast",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Salmon",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 208,
    protein: 22,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Tuna",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 184,
    protein: 30,
    carbs: 0,
    fat: 6,
    fiber: 0,
    sugar: 0,
    sodium: 50,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Tofu",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    sugar: 0.6,
    sodium: 7,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Lentils",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Chickpeas",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 139,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 7,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Black Beans",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    sugar: 0.3,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Kidney Beans",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 8.7,
    carbs: 22.8,
    fat: 0.5,
    fiber: 6.4,
    sugar: 0.3,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Greek Yogurt",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.6,
    sodium: 36,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Cottage Cheese",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 364,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Lunch", "Snacks"]
  },
  {
    name: "Milk",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    calories: 42,
    protein: 3.4,
    carbs: 4.8,
    fat: 1.0,
    fiber: 0,
    sugar: 5.1,
    sodium: 44,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast"]
  },
  {
    name: "Almonds",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Walnuts",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Peanuts",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 567,
    protein: 25.8,
    carbs: 16.1,
    fat: 49.2,
    fiber: 8.5,
    sugar: 4.7,
    sodium: 18,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Cashews",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.8,
    fiber: 3.3,
    sugar: 5.9,
    sodium: 12,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Pumpkin Seeds",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 559,
    protein: 30.2,
    carbs: 10.7,
    fat: 49.1,
    fiber: 6,
    sugar: 1.4,
    sodium: 7,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Sunflower Seeds",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 584,
    protein: 20.8,
    carbs: 20,
    fat: 51.5,
    fiber: 8.6,
    sugar: 2.6,
    sodium: 9,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Chia Seeds",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 486,
    protein: 16.5,
    carbs: 42.1,
    fat: 30.7,
    fiber: 34.4,
    sugar: 0,
    sodium: 16,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Flax Seeds",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 534,
    protein: 18.3,
    carbs: 28.9,
    fat: 42.2,
    fiber: 27.3,
    sugar: 1.6,
    sodium: 30,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },

  // Dairy & Alternatives
  {
    name: "Cheese",
    category: "Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 402,
    protein: 25.8,
    carbs: 1.3,
    fat: 33.1,
    fiber: 0,
    sugar: 0.5,
    sodium: 621,
    foodPreference: "Vegetarian",
    mealType: ["Lunch", "Dinner", "Snacks"]
  },
  {
    name: "Butter",
    category: "Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81.1,
    fiber: 0,
    sugar: 0.1,
    sodium: 2,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Lunch", "Dinner"]
  },
  {
    name: "Cream",
    category: "Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 345,
    protein: 2.4,
    carbs: 3.8,
    fat: 35.8,
    fiber: 0,
    sugar: 3.8,
    sodium: 38,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Dinner"]
  },
  {
    name: "Soy Milk",
    category: "Dairy Alternatives",
    servingSize: 100,
    servingUnit: "g",
    calories: 54,
    protein: 3.3,
    carbs: 6.3,
    fat: 1.8,
    fiber: 0.6,
    sugar: 4.3,
    sodium: 51,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },
  {
    name: "Almond Milk",
    category: "Dairy Alternatives",
    servingSize: 100,
    servingUnit: "g",
    calories: 17,
    protein: 0.6,
    carbs: 1.3,
    fat: 1.1,
    fiber: 0.2,
    sugar: 1.2,
    sodium: 63,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },
  {
    name: "Oat Milk",
    category: "Dairy Alternatives",
    servingSize: 100,
    servingUnit: "g",
    calories: 47,
    protein: 1.0,
    carbs: 7.0,
    fat: 1.5,
    fiber: 0.8,
    sugar: 4.0,
    sodium: 46,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },

  // Seafood
  {
    name: "Shrimp",
    category: "Seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 85,
    protein: 20.1,
    carbs: 0.2,
    fat: 0.5,
    fiber: 0,
    sugar: 0,
    sodium: 119,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Sardines",
    category: "Seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 208,
    protein: 24.6,
    carbs: 0,
    fat: 11.5,
    fiber: 0,
    sugar: 0,
    sodium: 505,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Mackerel",
    category: "Seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 205,
    protein: 18.6,
    carbs: 0,
    fat: 13.9,
    fiber: 0,
    sugar: 0,
    sodium: 83,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Cod",
    category: "Seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 82,
    protein: 17.8,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    sugar: 0,
    sodium: 54,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Trout",
    category: "Seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 168,
    protein: 21.5,
    carbs: 0,
    fat: 8.5,
    fiber: 0,
    sugar: 0,
    sodium: 55,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Halibut",
    category: "Seafood",
    servingSize: 100,
    servingUnit: "g",
    calories: 91,
    protein: 20.7,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    sugar: 0,
    sodium: 58,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },

  // Meat
  {
    name: "Beef",
    category: "Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    sugar: 0,
    sodium: 72,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Pork",
    category: "Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 242,
    protein: 27,
    carbs: 0,
    fat: 14,
    fiber: 0,
    sugar: 0,
    sodium: 62,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Lamb",
    category: "Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 294,
    protein: 25.6,
    carbs: 0,
    fat: 20.5,
    fiber: 0,
    sugar: 0,
    sodium: 72,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Turkey Breast",
    category: "Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1.5,
    fiber: 0,
    sugar: 0,
    sodium: 55,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Duck Breast",
    category: "Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 200,
    protein: 23.5,
    carbs: 0,
    fat: 11.5,
    fiber: 0,
    sugar: 0,
    sodium: 75,
    foodPreference: "Non-Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },

  // Legumes
  {
    name: "Soybeans",
    category: "Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 173,
    protein: 16.6,
    carbs: 9.9,
    fat: 8.9,
    fiber: 6,
    sugar: 3,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Mung Beans",
    category: "Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 8.5,
    carbs: 23.7,
    fat: 0.5,
    fiber: 7.6,
    sugar: 2.7,
    sodium: 10,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Navy Beans",
    category: "Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 140,
    protein: 8.2,
    carbs: 26.1,
    fat: 0.6,
    fiber: 10.5,
    sugar: 0.4,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Pinto Beans",
    category: "Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 143,
    protein: 9,
    carbs: 26.2,
    fat: 0.7,
    fiber: 9,
    sugar: 0.7,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Fava Beans",
    category: "Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 106,
    protein: 7.6,
    carbs: 19.7,
    fat: 0.4,
    fiber: 7.5,
    sugar: 1.8,
    sodium: 8,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },

  // Herbs & Spices
  {
    name: "Basil",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 44,
    protein: 3.2,
    carbs: 2.7,
    fat: 0.6,
    fiber: 1.6,
    sugar: 0.3,
    sodium: 4,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Cilantro",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.1,
    carbs: 3.7,
    fat: 0.5,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 46,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Parsley",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 36,
    protein: 2.3,
    carbs: 6.3,
    fat: 0.8,
    fiber: 3.3,
    sugar: 0.9,
    sodium: 56,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Mint",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 44,
    protein: 3.3,
    carbs: 8.4,
    fat: 0.7,
    fiber: 6.8,
    sugar: 0.9,
    sodium: 31,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Rosemary",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 131,
    protein: 3.3,
    carbs: 20.7,
    fat: 5.9,
    fiber: 14.1,
    sugar: 0.9,
    sodium: 26,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Thyme",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 101,
    protein: 5.6,
    carbs: 24.5,
    fat: 1.7,
    fiber: 14.0,
    sugar: 0.9,
    sodium: 9,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Oregano",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 9,
    carbs: 68.9,
    fat: 4.3,
    fiber: 42.8,
    sugar: 4.1,
    sodium: 25,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Cumin",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 375,
    protein: 17.8,
    carbs: 44.2,
    fat: 22.3,
    fiber: 10.5,
    sugar: 2.3,
    sodium: 168,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Turmeric",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 354,
    protein: 7.8,
    carbs: 64.9,
    fat: 9.9,
    fiber: 21.1,
    sugar: 3.2,
    sodium: 38,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Cinnamon",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 247,
    protein: 4,
    carbs: 80.6,
    fat: 1.2,
    fiber: 53.1,
    sugar: 2.2,
    sodium: 10,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Dinner"]
  },
  {
    name: "Black Pepper",
    category: "Herbs & Spices",
    servingSize: 100,
    servingUnit: "g",
    calories: 251,
    protein: 10.4,
    carbs: 63.9,
    fat: 3.3,
    fiber: 25.3,
    sugar: 0.6,
    sodium: 20,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },

  // Oils & Fats
  {
    name: "Olive Oil",
    category: "Oils & Fats",
    servingSize: 100,
    servingUnit: "g",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Coconut Oil",
    category: "Oils & Fats",
    servingSize: 100,
    servingUnit: "g",
    calories: 862,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Canola Oil",
    category: "Oils & Fats",
    servingSize: 100,
    servingUnit: "g",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Sunflower Oil",
    category: "Oils & Fats",
    servingSize: 100,
    servingUnit: "g",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Sesame Oil",
    category: "Oils & Fats",
    servingSize: 100,
    servingUnit: "g",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },

  // Beverages
  {
    name: "Coffee",
    category: "Beverages",
    servingSize: 100,
    servingUnit: "g",
    calories: 1,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },
  {
    name: "Tea",
    category: "Beverages",
    servingSize: 100,
    servingUnit: "g",
    calories: 1,
    protein: 0,
    carbs: 0.2,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Orange Juice",
    category: "Beverages",
    servingSize: 100,
    servingUnit: "g",
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    sugar: 8.4,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },
  {
    name: "Apple Juice",
    category: "Beverages",
    servingSize: 100,
    servingUnit: "g",
    calories: 46,
    protein: 0.1,
    carbs: 11.3,
    fat: 0.1,
    fiber: 0.2,
    sugar: 10.4,
    sodium: 5,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Green Tea",
    category: "Beverages",
    servingSize: 100,
    servingUnit: "g",
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 1,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },

  // Processed Foods
  {
    name: "Whole Grain Cereal",
    category: "Processed Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 350,
    protein: 10,
    carbs: 75,
    fat: 2,
    fiber: 10,
    sugar: 10,
    sodium: 150,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast"]
  },
  {
    name: "Granola",
    category: "Processed Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 471,
    protein: 13,
    carbs: 64,
    fat: 20,
    fiber: 8,
    sugar: 20,
    sodium: 50,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Peanut Butter",
    category: "Processed Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    sugar: 9,
    sodium: 429,
    foodPreference: "Vegan",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Jam",
    category: "Processed Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 0.4,
    carbs: 65,
    fat: 0.1,
    fiber: 1.5,
    sugar: 45,
    sodium: 10,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },
  {
    name: "Honey",
    category: "Processed Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 304,
    protein: 0.3,
    carbs: 82.4,
    fat: 0,
    fiber: 0.2,
    sugar: 82.1,
    sodium: 4,
    foodPreference: "Vegetarian",
    mealType: ["Breakfast", "Snacks"]
  },
  {
    name: "Maple Syrup",
    category: "Processed Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 260,
    protein: 0,
    carbs: 67,
    fat: 0.1,
    fiber: 0,
    sugar: 60.4,
    sodium: 12,
    foodPreference: "Vegan",
    mealType: ["Breakfast"]
  },

  // Condiments & Sauces
  {
    name: "Ketchup",
    category: "Condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 101,
    protein: 1.0,
    carbs: 26.9,
    fat: 0.1,
    fiber: 0.3,
    sugar: 22.3,
    sodium: 907,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Mustard",
    category: "Condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 66,
    protein: 3.7,
    carbs: 6.0,
    fat: 3.7,
    fiber: 3.3,
    sugar: 0.9,
    sodium: 1100,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Mayonnaise",
    category: "Condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 717,
    protein: 1.1,
    carbs: 2.7,
    fat: 79.0,
    fiber: 0,
    sugar: 0.9,
    sodium: 567,
    foodPreference: "Vegetarian",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Soy Sauce",
    category: "Condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 53,
    protein: 8.1,
    carbs: 4.9,
    fat: 0.6,
    fiber: 0.8,
    sugar: 0.6,
    sodium: 5493,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Vinegar",
    category: "Condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0,
    carbs: 0.8,
    fat: 0,
    fiber: 0,
    sugar: 0.4,
    sodium: 2,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },
  {
    name: "Hot Sauce",
    category: "Condiments",
    servingSize: 100,
    servingUnit: "g",
    calories: 11,
    protein: 0.5,
    carbs: 1.8,
    fat: 0.4,
    fiber: 0.3,
    sugar: 1.3,
    sodium: 2520,
    foodPreference: "Vegan",
    mealType: ["Lunch", "Dinner"]
  },

  // Snacks
  {
    name: "Popcorn",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 387,
    protein: 12.9,
    carbs: 77.8,
    fat: 4.5,
    fiber: 15.1,
    sugar: 0.9,
    sodium: 4,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Pretzels",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 383,
    protein: 10.3,
    carbs: 80.4,
    fat: 2.9,
    fiber: 3.5,
    sugar: 3.2,
    sodium: 1400,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Rice Cakes",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 389,
    protein: 7.9,
    carbs: 82.1,
    fat: 3.5,
    fiber: 1.5,
    sugar: 0.9,
    sodium: 127,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Trail Mix",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 462,
    protein: 14.4,
    carbs: 44.2,
    fat: 28.1,
    fiber: 6.9,
    sugar: 22.1,
    sodium: 17,
    foodPreference: "Vegan",
    mealType: ["Snacks"]
  },
  {
    name: "Granola Bar",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 471,
    protein: 13,
    carbs: 64,
    fat: 20,
    fiber: 8,
    sugar: 20,
    sodium: 50,
    foodPreference: "Vegetarian",
    mealType: ["Snacks"]
  },

];

const importFood = async () => {
  try {
    await connectDB();

    await Food.deleteMany();

    await Food.insertMany(foods);

    console.log("Foods Imported Successfully");

    process.exit();

  } catch (error) {
    console.log(error);

    process.exit(1);
  }
};

importFood();